language: java
jdk:
- oraclejdk8
branches:
  only:
  - master
  - develop
notifications:
  email:
    recipients:
    - architect@gmail.com
services:
- mysql
before_install:
- mysql -e 'CREATE DATABASE IF NOT EXISTS forge;'
script:
- mvn verify